# Generated by Django 4.2.4 on 2024-10-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_libraryhistory_feeshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fees_paid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='outstanding_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_fees',
        ),
    ]
