# Generated by Django 4.2.4 on 2024-10-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_student_fees_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryhistory',
            old_name='issued_to',
            new_name='student',
        ),
    ]
