# Generated by Django 4.2.4 on 2024-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_enrollment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
