# Generated by Django 4.2.4 on 2024-10-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_student_date_of_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=225)),
                ('book_author', models.CharField(max_length=200)),
                ('book_avilability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='libraryhistory',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='libraryhistory',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.library'),
        ),
    ]
