# Generated by Django 4.2.4 on 2024-10-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_library_libraryhistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryhistory',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
